name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
          py-version: [3.10, 3.11, 3.12]
    runs-on: [ ubuntu-latest, macos-14, windows-latest]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10, 3.11, 3.12
    